<a href="https://colab.research.google.com/github/dineshkumar8464/pandas/blob/main/NumPy_dinesh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing numPy

In [ ]:
import numpy as np

#Create Arrays

In [ ]:
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
b = np.aray([1,2,3,4,5])  # array not aray
b

AttributeError: module 'numpy' has no attribute 'aray'

creating some numpy arrays and functions


In [ ]:
arr1 = np.array ([1,2,3,4,5])
arr2 =np.array([6,7,8,9,10])
print(arr1)
print(arr2)

a1 = arr1 + arr2
a2 = arr1-arr2
a3 = arr1*arr2
a4 = arr2/arr1
print(a1)
print(a2)
print(a3)
print(a4)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
#addition
arr1 = np.array ([1,2,3,4,5])
arr2 =np.array([6,7,8,9,8])
print(arr1)

a1 = arr1 + arr2
a2 = arr1-arr2
a3 = arr1*arr2
a4 = arr2/arr1
print(a1)
print(a2)
print(a3)
print(a4)

[1 2 3 4 5]
[ 7  9 11 13 13]
[-5 -5 -5 -5 -3]
[ 6 14 24 36 40]
[6.         3.5        2.66666667 2.25       1.6       ]


#Create Arrays using Arange ()

**arange function** ( )


In [ ]:
array = np.arange(10)
array1=np.arange(10,20)
print(array)
print(array1)

a1= array + array1
a2= array - array1
a3= array * array1
a4= array / array1
print(a1)
print(a2)
print(a3)
print(a4)
print(" \n")


#create 2D array with arange function using reshape
array2 = np.arange(10).reshape(2,5)
print(array2)
print(" \n")

array3 = np.arange(10).reshape(5,2)
print(array3)
print(" \n")

array4 = np.arange(10).reshape(2,5)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
 

[[0 1 2 3 4]
 [5 6 7 8 9]]
 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
 

[[0 1 2 3 4]
 [5 6 7 8 9]]


#NUMPY VS PYTHON

Numpy is fast and convinent when compared to python

In [ ]:
import numpy as np
import sys
import time

#value for py and np
value =10000000

#python lists
list1 = range(value)
list2 = range(value)

#numpy arrays
array1 = np.arange(value)
array2 = np.arange(value)

# python list
start = time.time()
result = [(x+y) for x,y in zip(list1,list2)]
print("python list time took : ",(time.time() - start)*1000)

#numpy array
start = time.time()
print(array1 + array2)
print("numpy array time took : " ,(time.time() - start)*1000)


python list time took :  1219.3031311035156
[       0        2        4 ... 19999994 19999996 19999998]
numpy array time took :  162.78386116027832


#Basic Array Operations



*   FOR our better understanding the dimensions will be base on the square bracktes



1.   1D   --> [ values ]

2.  2D    --> [ [ values ] ]

3.  3D    --> [ [ [ values ] ] ]





In [ ]:
import numpy as np

#1D array --> array [ ]

a = np.array([1,2,3,4,5])
print("The dimension of the array is : ", a.ndim)
print(a)

#2dimesion array --> array [ [ ] ]

a2 = np.array([[1,2],[4,3],[3,4]])
print("The dimensions of the array is : ", a2.ndim)
print(a2)

#3dimension array --> array [ [ [ ] ] ]

a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("The dimensions of the array is : ", a3.ndim)
print(a3)



The dimension of the array is :  1
[1 2 3 4 5]
The dimensions of the array is :  2
[[1 2]
 [4 3]
 [3 4]]
The dimensions of the array is :  3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]




1.  **Itemsize**
2.  **size**
3.  **shape**
4.  **dtype**


In [ ]:
import numpy as np

#1D Array

a = np.array([1,2,3,4,5])
print(a)
print(a.itemsize)
print("")
print(a.size)
print("")
print(a.shape)
print("")
print(a.dtype)
print("")


#2d array

a2= np.array([[1,2],[3,4]])
print(a2)
print("")
print(a2.itemsize)
print("")
print(a2.size)
print("")
print(a2.shape)
print("")
print(a2.dtype)
print("")

#3d array

a3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)
print("")
print(a3.itemsize)
print("")
print(a3.size)
print("")
print(a3.shape)
print("")
print(a3.dtype)


[1 2 3 4 5]
8

5

(5,)

int64

[[1 2]
 [3 4]]

8

4

(2, 2)

int64

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

8

8

(2, 2, 2)

int64


**zeros and ones function**

In [ ]:
import numpy as np
a = np.zeros((2,3))
print(a)
print(" ")

b = np.ones((2,5))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


1.  **Range**
2.  **Arange**
3.  **Linspace**

In [ ]:
#range function
list1 = range(10)
print(list1)
print("")
print(list1[2])
print('')

list2 = range (0,10,2)
print(list2)
print('')
print(list2[3])
print


#arange function
array = np.arange(10)
print(array)
print('')
print(array[2])   #acces index
print('')

array1 = np.arange(0,10,2)
print(array1)
print('')
print(array1[3])   #acess index
print('')


array1 = np.arange(1,5)
print(array1)
print('')
print(array1[3])    #acess index
print('')

array2 = np.arange(1,10,2)
print(array2)
print('')
print(array2[3])     #acess index
print('')

array3 = np.arange(1,10,5)
print(array3)
print('')


array4 = np.arange(1,10,3)
print(array3[1])      #acess index
print('')

#linspace
#it increases the values upto 50 there is no step value will be given

arr = np.linspace(1,10)   # 1---------10, total 50 values will be displayed
print(arr)
print("")
a=np.linspace(10,15)
print(a)
print("")
arr1=np.linspace(1,10,5)     #there is a step value, so values printed upto 1-10
print(arr1)
print("")
arr4=np.linspace(1,10,3)
print(arr4)
print("")
arr2=np.linspace(1,10,20)
print(arr2)
print("")
arr3=np.linspace(1,10,3)
print(arr3)
print("")

range(0, 10)

2

range(0, 10, 2)

6
[0 1 2 3 4 5 6 7 8 9]

2

[0 2 4 6 8]

6

[1 2 3 4]

4

[1 3 5 7 9]

7

[1 6]

6

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]

[10.         10.10204082 10.20408163 10.30612245 10.40816327 10.51020408
 10.6122449  10.71428571 10.81632653 10.91836735 11.02040816 11.12244898
 11.2244898  11.32653061 11.42857143 11.53061224 11.63265306 11.73469388
 11.83673469 11.93877551 12.04081633 12.14285714 12.2

1.  **shape**
2.  **reshape**
3.  **ravel**


In [ ]:
import numpy as np
a= np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.ndim)
print("")
print(a.shape)
print("")

#reshape takes values into an oderwise such as :
#array[] [2,3],[4,5],[6,7] ] --> 2,3,4,5,6,7....
#it can print the values in order based on the requirements
# seee the below code carefully
print(a.reshape(2,3))
print("")
print(a.reshape(3,2))
print("")
print(a.reshape(6,1))
print("")
print(a.reshape(1,6))


[[1 2]
 [3 4]
 [5 6]]
2

(3, 2)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ravel makes the flattend array means any dimesional array can be converted into 1d array
#it just save as like a copy
#for permenant changes we can use inplace= True

a= np.array([[1,2],[3,4],[5,6]])
print(a.ravel())


[1 2 3 4 5 6]


**aggregate functions**

1.  sum
2.  min
3.  max
4.  mean ..... etc



In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5],[5,3,2,3,1]])
print(a)
print(a.ndim)
print("")
print(np.sum(a))
print("")
print(np.min(a))
print("")
print(np.max(a))
print("")
print(np.mean(a))

#axis (x=0 for columns, x=1 for rows)
# we are using magical operators (__add__ ,__sub__ ) for coloumn and rowwise additions

print(np.sum(a,axis=0))                  # columnwise addition
print("")
print(np.sum(a,axis=1))                  # rowwise addition
print("")

#sqrt, std( we can call it as numpy or np.sqrt(), numpy or np.stdev())
b= np.array([[4,16],[25,64],[9,16]])
print(a.ndim)
print(np.sqrt(b))
print("")
print(np.std(b))





[[1 2 3 4 5]
 [5 3 2 3 1]]
2

29

1

5

2.9
[6 5 5 7 6]

[15 14]

2
[[2. 4.]
 [5. 8.]
 [3. 4.]]

19.737161790783286


**operations in numpy that python cant do directly**

In [ ]:
import numpy as np
a = np.array([[1,2],[5,10]])
b = np.array([[6,7],[9,10]])

#in python we cannot perform these (add,sub,mul,div) operations on array
#we can do these type of operations on arrays in python, we can use (__add__, __mul__ ) magical operators but we can easily do in numpy
#numpy is more convienent

print(a+b)
print("")
print(a-b)
print("")
print(a*b)
print("")
print(a/b)
print("")
print(a%b)

[[ 7  9]
 [14 20]]

[[-5 -5]
 [-4  0]]

[[  6  14]
 [ 45 100]]

[[0.16666667 0.28571429]
 [0.55555556 1.        ]]

[[1 2]
 [5 0]]


**matrix product**

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a.dot(b))

[[19 22]
 [43 50]]


#Indixing and slicing


   



**1D Array**

In [ ]:
import numpy as np

#one dimensional array
#list
n=[1,2,3,4,5,6]
print(n)
print("")
print(n[0:3])
print("")
print(n[-1])
print("")

#1Darray in numpy
#same as list slicing and indexing in python with some diffrences
a= np.array([1,2,3,4,5])
print(a)
print("")
print(a[0:3])
print("")
print(a[-1])


[1, 2, 3, 4, 5, 6]

[1, 2, 3]

6

[1 2 3 4 5]

[1 2 3]

5


**2D array**

In [ ]:
import numpy as np
a= np.array([[1,2,3],[5,6,7],[9,3,2]])
print(a)
print(a.ndim)
print(" ")
print(a[0:1])
print(" ")
print(a[0:2])
print(" ")
print(a[0:3])
print(" ")
print("0:2 represents 0&1'th rows and the '2' represents the 2nd coloumn elements in the 0 and 1 rows")
print(a[0:2,2])
print(" ")
print(a[-1])
print("")
print("-1 represents last row '0:2' represent 0 and 1'th coloumn values")
print(a[-1,0:2])
print(" ")
print("we want print 2nd column values such as 2,6,3 :")
print(a[0:4,1])
print("")
print("we want to print 2nd row values such as 5,6,7")
print(a[-2,0:3]) #(a[1,0:3])

[[1 2 3]
 [5 6 7]
 [9 3 2]]
2
 
[[1 2 3]]
 
[[1 2 3]
 [5 6 7]]
 
[[1 2 3]
 [5 6 7]
 [9 3 2]]
 
0:2 represents 0&1'th rows and the '2' represents the 2nd coloumn elements in the 0 and 1 rows
[3 7]
 
[9 3 2]

-1 represents last row '0:2' represent 0 and 1'th coloumn values
[9 3]
 
we want print 2nd column values such as 2,6,3 :
[2 6 3]

we want to print 2nd row values such as 5,6,7
[5 6 7]


loop iterate

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[9,3,2]])
print(a)
print("")
for i in a:
  print(i)

#for flattend (ravel) means any array converted into 1dimensional array
print("")
for j in a.flat:       # like ravel
  print(j)



[[1 2 3]
 [4 5 6]
 [9 3 2]]

[1 2 3]
[4 5 6]
[9 3 2]

1
2
3
4
5
6
9
3
2


#Stacking

1.  VSTACK
2.  HSTACK
3.  VSPLIT
4.  HSPLIT



**vstack**

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print("")
print(b)
print("")
print(np.vstack((a,b)))   # vertical ( --- )

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**hstack**


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print("")
print(b)
print("")
# 1st row --> a[1]b
# 2nd row --> a[2]b[1]

print(np.hstack((a,b)))   # horixontal ( | )

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


1. **vsplit**
2. **hsplit**

In [ ]:
import numpy as np
a=np.arange(30).reshape(2,15)              # create 2D array with reshape function
print(a)
print("")

#vsplit function     -- >  array [ [ A1 , A2 , A3 , A4 ]] the vsplit looks like

print(np.vsplit(a,2))
value = np.vsplit(a,2)
print("")
print(value[0])
print("")
print(value[1])
print("\n")
print("horizontal split :")


#hsplit function        -- > array [[A1,
                                    #A2 ,
                                    #A3 ,
                                    #A4]] the hsplit looks like

print(np.hsplit(a,3))
result = np.hsplit(a,3)
print(result[0])
print("")
print(result[1])
print("")
print(result[2])
print("")







[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]

[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


horizontal split :
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]

[[ 5  6  7  8  9]
 [20 21 22 23 24]]

[[10 11 12 13 14]
 [25 26 27 28 29]]



**Indexing with boolean values**

In [ ]:
import numpy as np
a= np.arange(12).reshape( 3,4)
print(a)
print("")
b=a>5
print(b)
print("")
print(a[b])
a[b]=-1
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

[ 6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5 -1 -1]
 [-1 -1 -1 -1]]


read file


In [ ]:
import numpy as np
x=np.array([[1,2,3],[3,4,5],[6,7,8]])
np.savetxt("test.txt",x)

y=np.loadtxt("test.txt")
print(y)

[[1. 2. 3.]
 [3. 4. 5.]
 [6. 7. 8.]]


**Iterate array**


In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
print(a)
print(" ")

#loop
#horizontal iteration
for i in a:
  print(i)

#vertical iteration
print("")
for j in a:
  for k in j:
    print(k)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

0
1
2
3
4
5
6
7
8
9
10
11


#np.nditer()

1. **c oder - (c and  nditer)  print elements in column wise
2.   f order -( only fortran) print elements in row wise**

c order and f order only for the read only modes
we can not perform modifiactions in this methods
for example
 i[...] =i*i
  print(i)
we get an error as the method as for read only

we wanna apply modifiactions we can use opflags['readwrite']

**DEFAULT ORDER**


1. It can print in rowwise by default

In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
print(a)
print(" ")

for x in np.nditer(a):
  print(x)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
0
1
2
3
4
5
6
7
8
9
10
11


**C ORDER**

In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
print(a)
print(" ")
for j in np.nditer(a,order='C'):
  print(j)


# this method is only for read only, no write (modifications ) will be done
# EXAMPLE --> j[...] =j*i
# print(j)
# we can run this modification of multiplication we get an error


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
0
1
2
3
4
5
6
7
8
9
10
11


**F ORDER**

In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
print(a)
print(" ")
for i in np.nditer(a,order='F'):
  print(i)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
0
4
8
1
5
9
2
6
10
3
7
11


**flags**

*   it can help to print the values of horizontal or vertical format in to an array format

*     ex : 1 2 3 4 5 6                  
                        11           
                        21  -->    [1,2,3]
                        31         [4,5,6]
                        41         [11,21,31]
                        51         [41,51,61]
                        61





In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
print(a)
print(" ")
for j in np.nditer(a,order='F',flags=['external_loop']):        #for create output like in an array format
  print(j)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
import numpy as np
a=np.arange(12).reshape (3,4)
for i in np.nditer(a,op_flags=['readwrite']):                 # using readwrite in nditer for modifications
  i[...] =i*i
  print(i)

#covert every number into squares
print(a)

0
1
4
9
16
25
36
49
64
81
100
121
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
